info:
  title: ShopKart Product API
  version: 1.0.0
openapi: 3.0.1
paths:
  /products:
    get:
      responses:
        "200":
          description: Successfully retrieved the product list
      summary: Get list of ShopKart products
