openapi: 3.0.1
info:
  title: ShopKart Product API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get list of ShopKart products
      responses:
        '200':
          description: Successfully retrieved the product list
