name: Deploy API to WSO2 via REST API

on:
  push:
    branches: [ main ]

jobs:
  # ---------------------------
  # List APIs
  # ---------------------------
  list-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.5.0/apictl-4.5.0-linux-amd64.tar.gz
          tar -xzf apictl-4.5.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Verify apictl version
        run: apictl version
