name: Deploy API to WSO2 via REST API

on:
  push:
    branches: [ main ]

jobs:
  import-apis:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.5.0/apictl-4.5.0-linux-amd64.tar.gz
          tar -xzf apictl-4.5.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Verify apictl version
        run: apictl version

      - name: Add Dev Environment
        shell: bash
        run: |
          DEV_APIM=${{ secrets.WSO2_ENV_URL }}
          apictl add env dev --apim https://$DEV_APIM

      - name: Login to Dev
        run: |
          apictl login dev -u "${{ secrets.WSO2_USERNAME }}" -p "${{ secrets.WSO2_PASSWORD }}" -k

      - name: Import API to Dev
        run: |
          apictl import api -f bank-demo/sample-api/deploy/dev/ProductAPI/ -e dev --preserve-provider=false -k --update
