name: Deploy API to WSO2 via REST API

on:
  push:
    branches: [ main ]

jobs:
  prepare-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
  install-apictl:
    runs-on: ubuntu-latest
    needs: [prepare-workspace]
    steps:
      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.5.0/apictl-4.5.0-linux-amd64.tar.gz
          tar -xzf apictl-4.5.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Verify installation
        run: apictl version
        
  environment-login:
    needs: [install-apictl]
    runs-on: ubuntu-latest
    steps:
      - name: Add Dev Environment
        shell: bash
        run: |
          DEV_APIM=${{ secrets.WSO2_ENV_URL }}
          apictl add env dev --apim https://$DEV_APIM

      - name: Login to Dev
        run: |
          apictl login dev -u "${{ secrets.WSO2_USERNAME }}" -p "${{ secrets.WSO2_PASSWORD }}" -k
  
  import-apis:
    needs: [environment-login]
    runs-on: ubuntu-latest
    steps:
      - name: Import API to Dev
        run: |
          apictl import api -f bank-demo/sample-api/deploy/dev/ProductAPI/ -e dev --preserve-provider=false -k --update
