name: Deploy API to WSO2 via REST API

on:
  push:
    branches: [ main ]

jobs:
  # ---------------------------
  # List APIs
  # ---------------------------
  list-apis:
    runs-on: ubuntu-latest

    steps:
      - name: Install apictl
        run: |
          wget https://github.com/wso2/product-apim-tooling/releases/download/v4.5.0/apictl-4.5.0-linux-amd64.tar.gz
          tar -xzf apictl-4.5.0-linux-amd64.tar.gz
          chmod +x apictl/apictl
          sudo mv apictl/apictl /usr/local/bin/

      - name: Verify apictl version
        run: apictl version

      - name: Add Dev Environment
        run: |
          apictl add env dev --apim https://${{ secrets.WSO2_DEV_APIM }}

      - name: Login to Dev
        env:
          APIM_USERNAME: ${{ secrets.APIM_USERNAME }}
          APIM_PASSWORD: admin
        run: |
          echo "Logging into dev environment..."
          apictl login dev -u admin -p $APIM_PASSWORD -k

      - name: List APIs in Dev Environment
        run: |
          echo "Listing APIs in 'dev' environment with extra info..."
          apictl list apis -e dev -v
